import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Queue;
import java.util.Set;

public class Solver {

    private final BattleBoard board;

    /**
     * Creates a solver for the specified battle board.
     *
     * @param board the board that the solver will search
     */
    public Solver(BattleBoard board) {
        this.board = board;
    }

    /**
     * Encodes the compact HP state for duplicate-state detection.
     *
     * @param hp the current health of every ship
     * @return a string representation of the HP state
     */
    private String encode(byte[] hp) {
        return Arrays.toString(hp);
    }

    /**
     * Reconstructs one attack sequence by following parent links.
     *
     * @param nodes all states generated by BFS
     * @param goalIndex the index of the first goal state
     * @return the attack sequence from the initial state to the goal
     */
    private List<Attack> reconstruct(
            List<Node> nodes,
            int goalIndex) {

        List<Attack> result = new ArrayList<>();
        int index = goalIndex;

        while (true) {
            Node node = nodes.get(index);

            if (node.parentIndex == -1) {
                break;
            }

            result.add(board.getAttack(node.attackedShip));
            index = node.parentIndex;
        }

        Collections.reverse(result);
        return result;
    }

    /**
     * Finds one shortest attack sequence using breadth-first search.
     * BFS stops immediately when it reaches the first goal state.
     *
     * @param initialHp the initial health of every ship
     * @return one shortest attack sequence, or an empty list if no solution exists
     * @throws IllegalArgumentException if the initial health array is invalid
     */
    public List<Attack> solve(byte[] initialHp) {
        if (initialHp == null
                || initialHp.length != board.getShipCount()) {
            throw new IllegalArgumentException(
                    "Initial HP array length must be ".concat(
                            String.valueOf(board.getShipCount())));
        }

        // Search Queue stores indexes of states waiting for BFS processing.
        Queue<Integer> searchQueue = new ArrayDeque<>();

        // Nodes store compact HP states and parent information for reconstruction.
        List<Node> nodes = new ArrayList<>();

        // Visited prevents the same HP state from being expanded repeatedly.
        Set<String> visited = new HashSet<>();

        Node root = new Node(
                initialHp.clone(),
                -1,
                -1);

        nodes.add(root);
        searchQueue.offer(0);
        visited.add(encode(initialHp));

        while (!searchQueue.isEmpty()) {
            int currentIndex = searchQueue.poll();
            Node current = nodes.get(currentIndex);

            // The first goal found by BFS is guaranteed to be optimal.
            if (board.isDestroyed(current.hp)) {
                return reconstruct(nodes, currentIndex);
            }

            // Try every living ship as the next direct attack.
            for (int ship = 0; ship < board.getShipCount(); ship++) {
                if (current.hp[ship] <= 0) {
                    // Destroyed ships cannot be selected again.
                    continue;
                }

                // BattleBoard applies one attack and its explosion chain.
                byte[] nextHp = board.attack(current.hp, ship);
                String key = encode(nextHp);

                if (!visited.add(key)) {
                    // Skip a state that has already been reached.
                    continue;
                }

                // Save the parent and selected ship for reconstruction.
                nodes.add(new Node(
                        nextHp,
                        currentIndex,
                        ship));

                searchQueue.offer(nodes.size() - 1);
            }
        }

        return List.of();
    }
}
